import type { UILanguage } from '../types/index.js';

export function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
}

export function formatDate(isoString: string): string {
  try {
    const d = new Date(isoString);
    return d.toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return isoString;
  }
}

// Lightweight i18n translations dictionary for Khmer and English
export const translations = {
  en: {
    appTitle: 'Dubber Pro',
    appSubtitle: 'AI Story Summarizer, Translator & Voice Cloning Studio',
    navHome: 'Studio',
    navVoices: 'Voice Lab',
    storyInputLabel: 'Story Text',
    storyInputPlaceholder: 'Paste or type your story here in any language (Khmer, English, etc.)...',
    uploadStoryFile: 'Upload Text (.txt)',
    actionLabel: 'Select Action',
    actionSummarize: 'Summarize',
    actionTranslate: 'Translate',
    actionBoth: 'Summarize + Translate',
    targetLangLabel: 'Target Language',
    summaryLengthLabel: 'Summary Length',
    lengthShort: 'Short',
    lengthMedium: 'Medium',
    lengthLong: 'Long',
    styleLabel: 'Voice Style',
    styleNews: 'News Broadcast',
    styleHorror: 'Horror Story',
    styleSponsor: 'Sponsor Promo',
    styleGeneral: 'General Story',
    ttsStyleLabel: 'Voice Reading Style',
    processButton: 'Process Story',
    processing: 'Processing with Claude AI...',
    summaryHeading: 'Story Summary',
    translationHeading: 'Full Translation',
    copyText: 'Copy Text',
    copied: 'Copied!',
    voiceSelectLabel: 'Narrator Voice',
    listenButton: 'Listen Audio',
    generatingAudio: 'Generating Speech...',
    voiceLabTitle: 'Custom Voice Cloning Lab',
    voiceLabSubtitle: '10 Built-in 100% Human Khmer Voices (5 Female, 5 Male) or clone your custom voice sample.',
    recordTab: 'Record Voice',
    uploadTab: 'Upload Audio',
    voiceNameLabel: 'Voice Name',
    voiceNamePlaceholder: 'e.g. My Narrator Voice, Grandpa, Sokha...',
    recordInstructions: 'Speak clearly for 15-30 seconds in a quiet room.',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    rerecord: 'Record Again',
    uploadInstructions: 'Upload an audio sample (.mp3, .wav, .m4a, max 10MB)',
    consentText: 'I own this voice or have explicit permission to clone it. I accept full responsibility for its usage.',
    cloneButton: 'Create Voice Clone',
    cloning: 'Cloning Voice...',
    clonedVoicesTitle: 'Your Cloned Voices',
    noClonedVoices: 'No cloned voices yet. Record or upload a sample above.',
    deleteVoice: 'Delete',
    builtInBadge: 'Built-in',
    clonedBadge: 'Custom Clone',
    audioPlayerTitle: 'Audio Player',
    coreTools: 'Navigation',
    navStudio: 'Story Studio',
    navDubbing: 'Video Dubbing',
    navPresets: 'Sample Stories',
    presetKhmer: 'Khmer Tale (Bird & Turtle)',
    presetEnglish: 'Tonle Sap Fisherman',
    systemReady: 'System Ready',
    collapseSidebar: 'Collapse',
    expandSidebar: 'Expand',
    activeModel: 'Claude 3.5 Sonnet',
    voiceEngines: 'Azure & ElevenLabs',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    navDownloader: 'Video Downloader',
    downloaderTitle: 'Universal Media Downloader',
    downloaderSubtitle: 'Download high-quality videos & MP3 audio from YouTube, Facebook, TikTok, Instagram, and more.',
    videoUrlPlaceholder: 'Paste video link here (YouTube, Facebook, TikTok, Instagram, Vimeo, etc.)...',
    fetchVideoBtn: 'Analyze Link',
    fetchingVideo: 'Analyzing Video...',
    supportedSites: 'Supported Platforms',
    videoDetails: 'Video Overview',
    selectQuality: 'Choose Resolution / Format',
    downloadVideoBtn: 'Download Now',
    downloadingMedia: 'Downloading & Processing...',
    downloadSuccess: 'Download completed successfully!',
    sendToStudio: 'Use in Story Studio',
    sendToVoiceLab: 'Clone from this Audio',
    invalidUrlError: 'Please enter a valid URL.',
    pasteFromClipboard: 'Paste Link',
  },
  km: {
    appTitle: 'ឌុបប័រ ប្រូ (Dubber Pro)',
    appSubtitle: 'កម្មវិធីសង្ខេប បកប្រែរឿង និងក្លូនសំឡេង AI សម្រាប់ភាសាខ្មែរ',
    navHome: 'ទំព័រដើម',
    navVoices: 'បន្ទប់ពិសោធន៍សំឡេង',
    storyInputLabel: 'អត្ថបទរឿង',
    storyInputPlaceholder: 'សូមបិទភ្ជាប់ ឬវាយបញ្ចូលរឿងរបស់អ្នកនៅទីនេះ ជាភាសាខ្មែរ ឬភាសាដទៃទៀត...',
    uploadStoryFile: 'បញ្ចូលឯកសារ (.txt)',
    actionLabel: 'ជ្រើសរើសសកម្មភាព',
    actionSummarize: 'សង្ខេប',
    actionTranslate: 'បកប្រែ',
    actionBoth: 'សង្ខេប + បកប្រែ',
    targetLangLabel: 'ភាសាគោលដៅ',
    summaryLengthLabel: 'ប្រវែងសង្ខេប',
    lengthShort: 'ខ្លី',
    lengthMedium: 'មធ្យម',
    lengthLong: 'វែង',
    styleLabel: 'ទម្រង់សម្លេង/អត្ថបទ',
    styleNews: 'អានព័ត៌មាន',
    styleHorror: 'និទានរឿងរន្ធត់',
    styleSponsor: 'បញ្ចូលសម្លេង Sponsor',
    styleGeneral: 'និទានទូទៅ',
    ttsStyleLabel: 'ទម្រង់សម្លេងអាន (TTS)',
    processButton: 'ដំណើរការអត្ថបទ',
    processing: 'កំពុងដំណើរការជាមួយ Claude AI...',
    summaryHeading: 'សេចក្ដីសង្ខេបរឿង',
    translationHeading: 'ការបកប្រែពេញលេញ',
    copyText: 'ចម្លងអត្ថបទ',
    copied: 'បានចម្លង!',
    voiceSelectLabel: 'សំឡេងអ្នកអាន',
    listenButton: 'ស្ដាប់ជាសំឡេង',
    generatingAudio: 'កំពុងបង្កើតសំឡេង...',
    voiceLabTitle: 'ការក្លូនសំឡេង និងបណ្ណាល័យសំឡេងខ្មែរ (Voice Cloning Lab)',
    voiceLabSubtitle: 'បណ្ណាល័យសំឡេងខ្មែរដូចមនុស្ស ១០០% ចំនួន ១០ សំឡេង (ស្រី ៥, ប្រុស ៥) ឬថត/បញ្ចូលឯកសារដើម្បី Clone សំឡេងផ្ទាល់ខ្លួនថ្មី។',
    recordTab: 'ថតសំឡេងផ្ទាល់',
    uploadTab: 'បញ្ចូលឯកសារសំឡេង',
    voiceNameLabel: 'ឈ្មោះសំឡេង',
    voiceNamePlaceholder: 'ឧទាហរណ៍៖ សំឡេងសុខា, អ្នកនិទានរឿង...',
    recordInstructions: 'សូមនិយាយឲ្យបានច្បាស់ប្រមាណ ១៥ ទៅ ៣០ វិនាទីនៅកន្លែងស្ងាត់។',
    startRecording: 'ចាប់ផ្ដើមថត',
    stopRecording: 'បញ្ឈប់ការថត',
    rerecord: 'ថតម្ដងទៀត',
    uploadInstructions: 'បញ្ចូលឯកសារសំឡេង (.mp3, .wav, .m4a, .webm, អតិបរមា 50MB)',
    consentText: 'ខ្ញុំជាម្ចាស់សំឡេងនេះ ឬមានការអនុញ្ញាតជាក់លាក់ក្នុងការក្លូនសំឡេងនេះ។ ខ្ញុំទទួលខុសត្រូវទាំងស្រុងចំពោះការប្រើប្រាស់។',
    cloneButton: 'បង្កើតសំឡេងក្លូន',
    cloning: 'កំពុងក្លូនសំឡេង...',
    clonedVoicesTitle: 'សំឡេងក្លូនរបស់អ្នក',
    noClonedVoices: 'មិនទាន់មានសំឡេងក្លូននៅឡើយទេ។ សូមថត ឬបញ្ចូលគំរូសំឡេងខាងលើ។',
    deleteVoice: 'លុប',
    builtInBadge: 'មានស្រាប់',
    clonedBadge: 'សំឡេងផ្ទាល់ខ្លួន',
    audioPlayerTitle: 'ឧបករណ៍ចាក់សំឡេង',
    coreTools: 'ម៉ឺនុយចម្បង',
    navStudio: 'ស្ទូឌីយោសង្ខេប & បកប្រែ',
    navDubbing: 'បញ្ចូលសំឡេងវីដេអូ',
    navPresets: 'គំរូរឿងសាកល្បង',
    presetKhmer: 'រឿងកូនចាប និងអណ្ដើក',
    presetEnglish: 'រឿងអ្នកនេសាទបឹងទន្លេសាប',
    systemReady: 'ប្រព័ន្ធរួចរាល់',
    collapseSidebar: 'បង្រួម',
    expandSidebar: 'ពង្រីក',
    activeModel: 'Claude 3.5 Sonnet',
    voiceEngines: 'Azure & ElevenLabs',
    themeLight: 'ពន្លឺ (Light)',
    themeDark: 'ងងឹត (Dark)',
    navDownloader: 'ទាញយកវីដេអូ',
    downloaderTitle: 'កម្មវិធីទាញយកវីដេអូ & សំឡេងគ្រប់វេបសាយ',
    downloaderSubtitle: 'ទាញយកវីដេអូច្បាស់កម្រិតខ្ពស់ និង MP3 ពី YouTube, Facebook, TikTok, Instagram និងវេបសាយជាច្រើនទៀត។',
    videoUrlPlaceholder: 'បិទភ្ជាប់តំណភ្ជាប់វីដេអូនៅទីនេះ (YouTube, Facebook, TikTok, Instagram...)...',
    fetchVideoBtn: 'វិភាគវីដេអូ',
    fetchingVideo: 'កំពុងវិភាគ...',
    supportedSites: 'បណ្ដាញសង្គមដែលគាំទ្រ',
    videoDetails: 'ព័ត៌មានវីដេអូ',
    selectQuality: 'ជ្រើសរើសគុណភាព / ទម្រង់ឯកសារ',
    downloadVideoBtn: 'ទាញយកឥឡូវនេះ',
    downloadingMedia: 'កំពុងទាញយក & រៀបចំឯកសារ...',
    downloadSuccess: 'ការទាញយកបានជោគជ័យ!',
    sendToStudio: 'ប្រើក្នុងស្ទូឌីយោនិទានរឿង',
    sendToVoiceLab: 'ក្លូនសំឡេងពីវីដេអូនេះ',
    invalidUrlError: 'សូមបញ្ចូលតំណភ្ជាប់វីដេអូដែលត្រឹមត្រូវ។',
    pasteFromClipboard: 'បិទភ្ជាប់ Link',
  },
} as const;

export function t(key: keyof (typeof translations)['en'], lang: UILanguage = 'en'): string {
  return translations[lang]?.[key] || translations['en'][key] || key;
}
